TaskHub.Web/Controllers/AssignmentsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TaskHub.Core.Domain.Entities;
using TaskHub.Core.DTO;
using TaskHub.Core.ServiceContracts;

namespace TaskHub.Web.Controllers
{
    public class AssignmentsController : Controller
    {
        private readonly IAssignmentGetterService _assignmentGetterService;
        private readonly IAssignmentAdderService _assignmentAdderService;
        private readonly IAssignmentUpdaterService _assignmentUpdaterService;
        private readonly IAssignmentDeleterService _assignmentDeleterService;

        public AssignmentsController(IAssignmentGetterService assignmentGetterService, IAssignmentAdderService assignmentAdderService, IAssignmentUpdaterService assignmentUpdaterService, IAssignmentDeleterService assignmentDeleterService)
        {
            _assignmentGetterService = assignmentGetterService;
            _assignmentAdderService = assignmentAdderService;
            _assignmentUpdaterService = assignmentUpdaterService;
            _assignmentDeleterService = assignmentDeleterService;
        }

        [Route("/{selectedDate:datetime?}")]
        public async Task<IActionResult> List(DateTime? selectedDate)
        {
            DateTime date = selectedDate != null ? selectedDate.Value : DateTime.Today.Date;

            ViewBag.SelectedDate = date.ToString("dd.MM.yyyy");
            ViewBag.SelectedDateLink = date.ToString("yyyy-MM-dd");

            Guid userID = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            ViewBag.UserID = userID;

            List<AssignmentResponse> assignments = await _assignmentGetterService.GetAssignmentsForDay(date, userID);

            AssignmentUpdateRequest? updateModel = null;

            if ((Guid?)TempData["UpdateID"] != null)
            {
                AssignmentResponse updateModelResponse = await _assignmentGetterService.GetAssignmentByID((Guid?)TempData["UpdateID"]);
                updateModel = updateModelResponse.ToUpdateRequest();
            }

            ListViewModel viewModel = new ListViewModel()
            {
                Assignments = assignments,
                UpdateRequest = updateModel == null ? null : updateModel
            };

            return View(viewModel);
        }


        [Route("/edit/{assignmentID:guid?}")]
        public async Task<IActionResult> RenderEditPartial(Guid assignmentID, DateTime selectedDate)
        {
            AssignmentResponse assignment = await _assignmentGetterService.GetAssignmentByID(assignmentID);

            ViewBag.SelectedDateLink = selectedDate.ToString("yyyy-MM-dd");

            return PartialView("_EditModalPartial", assignment.ToUpdateRequest());
        }

        [HttpPost]
        [Route("/update")]
        public async Task<IActionResult> EditAssignment(AssignmentUpdateRequest assignmentUpdateRequest, DateTime? selectedDate)
        {
            if (!ModelState.IsValid)
            {
                TempData["UpdateID"] = assignmentUpdateRequest.AssignmentID;
                return RedirectToAction("List", new {selectedDate = selectedDate?.ToString("yyyy-MM-dd")});
            }

            await _assignmentUpdaterService.ChangeContent(assignmentUpdateRequest);

            return RedirectToAction("List", new { selectedDate = selectedDate?.ToString("yyyy-MM-dd") });
        }

        [Route("/delete/{assignmentID:guid}")]
        public async Task<IActionResult> DeleteAssignment(Guid assignmentID, DateTime? selectedDate)
        {
            await _assignmentDeleterService.RemoveAssignment(assignmentID);

            return RedirectToAction("List", new { selectedDate =  selectedDate?.ToString("yyyy-MM-dd")});
        }

        [Route("/update-status/{assignmentID:guid}")]
        public async Task<IActionResult> ChangeAssignmentStatus(Guid assignmentID, DateTime? selectedDate)
        {
            await _assignmentUpdaterService.ChangeStatus(assignmentID);

            return RedirectToAction("List", new { selectedDate = selectedDate?.ToString("yyyy-MM-dd") });
        }

        [HttpPost]
        [Route("/add-task")]
        public async Task<IActionResult> AddTask(AssignmentAddRequest assignmentAddRequest, DateTime? selectedDate)
        {
            Guid userID = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            assignmentAddRequest.AuthorID = userID;

            if (!ModelState.IsValid)
            {
                return RedirectToAction("List", new { selectedDate = selectedDate?.ToString("yyyy-MM-dd") });
            }

            await _assignmentAdderService.AddAssignment(assignmentAddRequest);

            return RedirectToAction("List", new { selectedDate = selectedDate?.ToString("yyyy-MM-dd") });
        }
    }
}

TaskHub.Web/Views/Shared/_AddTaskPartial.cshtml
@model AssignmentAddRequest

<form id="add-task-form" class="form tasks-main__add-task__form" asp-controller="Assignments" asp-action="AddTask" asp-route-selectedDate="@ViewBag.SelectedDateLink">
    <input asp-for="Date" value="@ViewBag.SelectedDateLink" type="hidden">
    <input asp-for="AuthorID" value="@ViewBag.UserID" type="hidden">
    <div class="form__element">
        <div class="form__element__part form__element__input">
            <input asp-for="Content"><button><i class="fa-solid fa-plus"></i></button>
            <span class="form__validation-result" asp-validation-for="Content"></span>
        </div>
    </div>
</form>

TaskHub.Web/Views/Shared/_CalendarPartial.cshtml
<div class="calendar-container @ViewBag.CalendarClass">
    <div class="calendar__header">
        <p class="current-date"></p>
        <div class="icons">
            <span id="prev" class="material-symbols-rounded"><i class="fa-solid fa-circle-chevron-left"></i></span>
            <span id="next" class="material-symbols-rounded"><i class="fa-solid fa-circle-chevron-right"></i></span>
        </div>
    </div>
    <div class="calendar__content">
        <ul class="weeks">
            <li>Mon</li>
            <li>Tue</li>
            <li>Wed</li>
            <li>Thu</li>
            <li>Fri</li>
            <li>Sat</li>
            <li>Sun</li>
        </ul>
        <ul class="days" data-selected-date="@ViewBag.SelectedDate"></ul>
    </div>
</div>

TaskHub.Web/Views/Shared/_EditModalPartial.cshtml
@model AssignmentUpdateRequest

<div class="backdrop" id="backdrop">
    <div class="container container--narrow">
        <form class="form" method="post" asp-controller="Assignments" asp-action="EditAssignment">
            <div class="form__element">
                <input asp-for="AssignmentID" type="hidden">
                <input type="hidden" name="selectedDate" value="@ViewBag.SelectedDateLink">
                <div class="form__element__part form__element__label">
                    <label asp-for="Content">Edit task</label>
                </div>
                <div class="form__element__part form__element__input">
                    <input asp-for="Content" class="input--edit" spellcheck="false">
                    <span class="form__validation-result" asp-validation-for="Content"></span>
                </div>
            </div>
            <div class="form__element">
                <div class="form__element__part form__element__button">
                    <button type="submit" id="edit-task-submit-btn" class="btn btn--edit">Edit</button>
                    <button type="button" id="edit-task-cancel-btn" class="btn btn--edit">
                        @if(ViewBag.RenderedAlone == true)
                        {
                            <a asp-controller="Assignments" asp-action="List">Cancel</a>
                        } else
                        {
                            <span>Cancel</span>
                        }
                    </button>
                </div>
            </div>
            @ViewBag.Errors
        </form>
    </div>
</div>

TaskHub.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TaskHub - @ViewBag.Title</title>
    <link rel="icon" href="~/Assets/logo/favicon-color.png">
    <link rel="stylesheet" href="~/Styles/Root/root.min.css">
    @RenderSection("Styles", false)
    @RenderSection("ScriptsHead", false)
    <script src="https://kit.fontawesome.com/fb3001e2e6.js" crossorigin="anonymous" defer></script>
</head>
<body>
    @RenderBody()
</body>
</html>